name: Pull Request Webhook
on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  notify-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR notification
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "action": "${{ github.event.action }}",
              "pr_number": ${{ github.event.pull_request.number }},
              "pr_title": "${{ github.event.pull_request.title }}",
              "pr_state": "${{ github.event.pull_request.state }}",
              "pr_url": "${{ github.event.pull_request.html_url }}",
              "html_url": "${{ github.event.pull_request.html_url }}",
              "diff_url": "${{ github.event.pull_request.diff_url }}",
              "patch_url": "${{ github.event.pull_request.patch_url }}",
            }' \
            https://nhncommerce.loca.lt/api/v1/review?a=bbc